name: Run DUT tests on RPi
on:
  workflow_call:

jobs:
  run_DUT_tests:
    runs-on: self-hosted
    steps:
      - name: Initial setup
        run: |
          echo "/home/sidewalk/.local/bin" >> $GITHUB_PATH
          echo "/usr/local/sbin" >> $GITHUB_PATH
          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "/usr/sbin" >> $GITHUB_PATH
          echo "/usr/bin" >> $GITHUB_PATH
          echo "/sbin" >> $GITHUB_PATH
          echo "/bin" >> $GITHUB_PATH
          echo "/usr/share" >> $GITHUB_PATH
          echo "/snap/bin" >> $GITHUB_PATH
          rm -rf sidewalk artifacts twister-out* .west
      - uses: actions/checkout@v3
        with:
          path: internal_sidewalk

      - name: Update nrf
        run: |
          west init -l internal_sidewalk --mf internal_west.yml
          west update --narrow -o=--depth=1
          python3 -m pip install -r zephyr/scripts/requirements.txt
          ln -s internal_sidewalk sidewalk

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: tests-dut-artifacts

      - name: Run Tests
        run: |
          connected_DKs=`grep "connected: true" /hw_settings/hardware_map.yaml | wc -l`
          python3 sidewalk/scripts/ci/combine_twister_reports.py subsets/**/twister.json twister-out/twister.json
          python3 sidewalk/scripts/ci/combine_twister_reports.py subsets/**/testplan.json twister-out/testplan.json
          zephyr/scripts/twister -j $connected_DKs --no-clean -vvv --inline-logs --test-only --hardware-map /hw_settings/hardware_map.yaml --device-testing -T sidewalk/tests --retry-failed 2 --west-flash="--recover,--erase"

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests-DUT_result
          path: |
            twister-out/twister.xml
            twister-out/**/handler.log
            twister-out/**/device.log

      - name: Cleanup
        if: always()
        run: |
          rm -rf sidewalk internal_sidewalk artifacts twister-out* .west
